const users = [
    {
        "login": "john",
        "id": 1668,
        "node_id": "MDQ6VXNlcjE2Njg=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1668?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/john",
        "html_url": "https://github.com/john",
        "followers_url": "https://api.github.com/users/john/followers",
        "following_url": "https://api.github.com/users/john/following{/other_user}",
        "gists_url": "https://api.github.com/users/john/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/john/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/john/subscriptions",
        "organizations_url": "https://api.github.com/users/john/orgs",
        "repos_url": "https://api.github.com/users/john/repos",
        "events_url": "https://api.github.com/users/john/events{/privacy}",
        "received_events_url": "https://api.github.com/users/john/received_events",
        "type": "User",
        "site_admin": false,
        "name": "John McGrath",
        "company": "Amazon AWS",
        "blog": "https://twitter.com/wordie",
        "location": "San Francisco, CA",
        "email": null,
        "hireable": true,
        "bio": "I'm on the sustainability team at AWS, and prior to that co-founded Entelo. Interested in renewable energy, journalism, startups, and democracy.",
        "twitter_username": null,
        "public_repos": 54,
        "public_gists": 1,
        "followers": 117,
        "following": 48,
        "created_at": "2008-02-28T23:17:13Z",
        "updated_at": "2021-05-17T23:36:50Z"
      },
      {
        "login": "dave",
        "id": 925351,
        "node_id": "MDQ6VXNlcjkyNTM1MQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/925351?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dave",
        "html_url": "https://github.com/dave",
        "followers_url": "https://api.github.com/users/dave/followers",
        "following_url": "https://api.github.com/users/dave/following{/other_user}",
        "gists_url": "https://api.github.com/users/dave/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dave/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dave/subscriptions",
        "organizations_url": "https://api.github.com/users/dave/orgs",
        "repos_url": "https://api.github.com/users/dave/repos",
        "events_url": "https://api.github.com/users/dave/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dave/received_events",
        "type": "User",
        "site_admin": false,
        "name": "Dave Brophy",
        "company": null,
        "blog": "https://www.wildernessprime.com/",
        "location": null,
        "email": null,
        "hireable": null,
        "bio": null,
        "twitter_username": null,
        "public_repos": 117,
        "public_gists": 12,
        "followers": 207,
        "following": 1,
        "created_at": "2011-07-19T13:04:55Z",
        "updated_at": "2021-05-23T22:11:36Z"
      },
      {
        "login": "sonia",
        "id": 49149,
        "node_id": "MDQ6VXNlcjQ5MTQ5",
        "avatar_url": "https://avatars.githubusercontent.com/u/49149?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/sonia",
        "html_url": "https://github.com/sonia",
        "followers_url": "https://api.github.com/users/sonia/followers",
        "following_url": "https://api.github.com/users/sonia/following{/other_user}",
        "gists_url": "https://api.github.com/users/sonia/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/sonia/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sonia/subscriptions",
        "organizations_url": "https://api.github.com/users/sonia/orgs",
        "repos_url": "https://api.github.com/users/sonia/repos",
        "events_url": "https://api.github.com/users/sonia/events{/privacy}",
        "received_events_url": "https://api.github.com/users/sonia/received_events",
        "type": "User",
        "site_admin": false,
        "name": null,
        "company": null,
        "blog": "",
        "location": null,
        "email": null,
        "hireable": null,
        "bio": null,
        "twitter_username": null,
        "public_repos": 1,
        "public_gists": 0,
        "followers": 4,
        "following": 0,
        "created_at": "2009-01-25T15:20:35Z",
        "updated_at": "2017-08-15T06:20:43Z"
      },
      {
        "login": "akash",
        "id": 14871,
        "node_id": "MDQ6VXNlcjE0ODcx",
        "avatar_url": "https://avatars.githubusercontent.com/u/14871?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/akash",
        "html_url": "https://github.com/akash",
        "followers_url": "https://api.github.com/users/akash/followers",
        "following_url": "https://api.github.com/users/akash/following{/other_user}",
        "gists_url": "https://api.github.com/users/akash/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/akash/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/akash/subscriptions",
        "organizations_url": "https://api.github.com/users/akash/orgs",
        "repos_url": "https://api.github.com/users/akash/repos",
        "events_url": "https://api.github.com/users/akash/events{/privacy}",
        "received_events_url": "https://api.github.com/users/akash/received_events",
        "type": "User",
        "site_admin": false,
        "name": "Akash",
        "company": "wefarm",
        "blog": "",
        "location": null,
        "email": null,
        "hireable": null,
        "bio": null,
        "twitter_username": null,
        "public_repos": 13,
        "public_gists": 3,
        "followers": 15,
        "following": 0,
        "created_at": "2008-06-24T16:50:58Z",
        "updated_at": "2021-04-06T11:07:00Z"
      }
];

export { users };